// @ts-check
import js from '@eslint/js'
import tseslint from 'typescript-eslint'

/**
 * Only the product's own source is linted: `apps/` and `packages/`. ClaudeKit scripts under
 * `.claude/`, documentation, and build output are out of scope for this project's quality gate.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      // Generated by `next build` and gitignored; its triple-slash references are not ours.
      '**/next-env.d.ts',
      '**/node_modules/**',
      '**/drizzle/**',
      '**/migrations/**',
      '.claude/**',
      'plans/**',
      'docs/**',
    ],
  },
  {
    files: ['apps/**/*.{ts,tsx}', 'packages/**/*.ts', '*.{ts,js,mjs}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    rules: {
      // `tsc` already catches undefined identifiers, and does it more accurately
      // (no-undef does not understand type-only imports).
      'no-undef': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
)
